services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pocapi
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWTSECRET: SecretKeyToGenJWTs
      APP_JWTEXPIRATIONINMS: 86400000
      APP_SECURITY_ENABLED: "false"
    depends_on:
      - db
  db:
    image: 'postgres:13-alpine'
    environment:
      POSTGRES_DB: pocapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
