# App Properties
app.jwtSecret=SecretKeyToGenJWTs
app.jwtExpirationInMs=86400000
app.security.enabled=true

# Datasource Properties
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
